### PR TITLE
enh: Move package to vite for bundling + compress translations

### PR DESCRIPTION
**Pull request by susnux**
This includes a lot of changes:
1. Move to vite for bundling (reduces configurations and dependencies)
2. Compress translations by removing unneeded information, this reduces bundle size of **using** application by ~10kb
3. Explicitly import moment with locales, otherwise the locales are not included in bundles when using tree shaking like vite (fixes https://github.com/nextcloud/forms/issues/1856 and fixes https://github.com/nextcloud/tasks/issues/2448)

### CODE REVIEW

**Review by raimund-schluessler — APPROVED** [review]
Tested and works well with the Tasks app 👍

**Comment by raimund-schluessler** [comment]
I suppose this will be `2.0.0` of `nextcloud/moment`?

**Comment by Chartman123** [comment]
> I suppose this will be `2.0.0` of `nextcloud/moment`?

I'd expect to have a solution for #407 in a `2.0.0`...

**Comment by raimund-schluessler** [comment]
> > I suppose this will be `2.0.0` of `nextcloud/moment`?
> 
> I'd expect to have a solution for #407 in a `2.0.0`...

Well, I would not delay the next major release because of #407, because that will likely be a new package completely.

**Pull request merged**
